#!/usr/bin/python
import os, sys, datetime

if len(sys.argv) < 2:
   print('duh')
   sys.exit(-1)
   pass
timestamp=datetime.datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
known_hosts_path = os.path.join( os.getenv('HOME'), '.ssh/known_hosts')

kh0 = open(known_hosts_path, 'r').read().splitlines()
os.rename(known_hosts_path, known_hosts_path + ('.%s' % timestamp))
offender = int(sys.argv[1])
open(known_hosts_path, 'w').write('\n'.join(kh0[0:offender-1] + kh0[offender:]))
